name: BarkingDog Security Audit

on:
  repository_dispatch:
    types: [ bot_updated ]
  pull_request:
    branches: [ master ]
#  schedule:
#    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t barkingdog/scanner .

      - name: Run BarkingDog Scanner
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          AEGIS_SECRET_TOKEN: ${{ secrets.AEGIS_SECRET_TOKEN }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          BOT_DOMAIN: "Miami Auto Detailing services, booking, and pricing"
        run: |
          mkdir -p reports
          
          docker run --rm \
            -v ${{ github.workspace }}/reports:/app/reports \
            -e TARGET_URL=$TARGET_URL \
            -e AEGIS_SECRET_TOKEN=$AEGIS_SECRET_TOKEN \
            -e AI_API_KEY=$AI_API_KEY \
            -e TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
            -e TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID \
            -e BOT_DOMAIN="$BOT_DOMAIN" \
            barkingdog/scanner --url $TARGET_URL

      - name: Upload Security Report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: barkingdog-report
          path: reports/*.html
          retention-days: 14